/*
 Copyright (c) 2017 Videa Project Services GmbH

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
 and associated documentation files (the "Software"), to deal in the Software without restriction, 
 including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 and/or sell copies of the Software,and to permit persons to whom the Software is furnished to do so, 
 subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or substantial 
 portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
 NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
package de.teilautos.registration.parse;

import java.util.ResourceBundle;

/**
 * Reading of registration mail which has been generated by Web registration form. 
 */
public class ParseHandler {
	private ResourceBundle bundle = ResourceBundle.getBundle("registration-mail");
	
	public ParseHandler() {
	}

	public RegistrationModel parseContent(String content) {
		ContentParser parser = new ContentParser(content);
		RegistrationModel model = new RegistrationModel();
		
		model.setFirstname(parser.find(bundle.getString("firstname")));
		model.setSurname(parser.find(bundle.getString("surname")));
		model.setEmail(parser.find(bundle.getString("email")));
		model.setStreetNo(parser.find(bundle.getString("streetNo")));
		model.setPostCode(parser.find(bundle.getString("postCodeCity")));
		// TODO split post code and city
		model.setPhone(parser.find(bundle.getString("phone")));

		model.setPartnerProgram(PartnerProgramEnum.get(parser.find(bundle.getString("partnerProgram"))));
		model.setReference(parser.find(bundle.getString("reference")));
		
		boolean termsAndConditions = convertToBoolean(parser.find(bundle.getString("termsAndConditions")));
		model.setTermsAndConditionsAccepted(termsAndConditions);
		
		boolean dataPrivacyPolicy = convertToBoolean(parser.find(bundle.getString("dataPrivacyPolicy")));
		model.setDataPrivacyAccepted(dataPrivacyPolicy);
		
		boolean newsletter = convertToBoolean(parser.find(bundle.getString("newsletter")));
		model.setNewsletterWanted(newsletter);
		
		return model;
	}
	
	private boolean convertToBoolean(String answerYesNo) {
		if(bundle.getString("yes").equals(answerYesNo)) {
			return true;
		}
		if(bundle.getString("no").equals(answerYesNo)) {
			return false;
		}
		return false;
	}
	
}
